name: Update Submodules

on:
  schedule:
    # Run every 6 hours (adjust as needed)
    - cron: '0 */6 * * *'
  
  workflow_dispatch:
    # Allow manual trigger
    
  repository_dispatch:
    # Allow triggering from other repositories
    types: [submodule-updated]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Make update script executable
      run: chmod +x update-submodules.sh
    
    - name: Update submodules
      run: ./update-submodules.sh --auto-push
    
    - name: Create summary
      run: |
        echo "## Submodule Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Run ID**: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date)" >> $GITHUB_STEP_SUMMARY
        
        if git diff --quiet HEAD~1 HEAD 2>/dev/null; then
          echo "- **Status**: ✅ No updates needed" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: 🔄 Submodules updated" >> $GITHUB_STEP_SUMMARY
          echo "- **Changes**: See commit history" >> $GITHUB_STEP_SUMMARY
        fi
